LOCAL_PATH := $(call my-dir)

############ shared lib
include $(CLEAR_VARS)

include $(SDK_DIR)/Android.def

LOCAL_PRELINK_MODULE := false

LOCAL_MODULE := libhi_cipher
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)

LOCAL_MODULE_TAGS := optional

CFG_CIPHER_MINI_OR_NOT = y
LOCAL_CFLAGS := $(CFG_HI_CFLAGS)
LOCAL_CFLAGS += -DLOG_TAG=\"$(LOCAL_MODULE)\"

ifeq ($(CFG_HI_CHIP_TYPE),hi3712)
    ifeq ($(CFG_CIPHER_MINI_OR_NOT),y)
        LOCAL_CFLAGS += -DCFG_CIPHER_MINI
    endif
endif
ifeq ($(CFG_HI_CIPHER_MULTICIPHER_SUPPORT),y)
    LOCAL_CFLAGS += -DCFG_HI_CIPHER_MULTICIPHER_SUPPORT
endif
ifeq ($(CFG_HI_CIPHER_HASH_SUPPORT),y)
    LOCAL_CFLAGS += -DCFG_HI_CIPHER_HASH_SUPPORT
endif

#LOCAL_SRC_FILES := $(sort $(call all-c-files-under, ./))
LOCAL_SRC_FILES := unf_cipher.c

LOCAL_C_INCLUDES := $(COMMON_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_API_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_API_INCLUDE)

LOCAL_SHARED_LIBRARIES := libcutils libutils libhi_common

include $(BUILD_SHARED_LIBRARY)

############ static lib
include $(CLEAR_VARS)

include $(SDK_DIR)/Android.def

LOCAL_PRELINK_MODULE := false

LOCAL_MODULE := libhi_cipher
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)

LOCAL_MODULE_TAGS := optional

CFG_CIPHER_MINI_OR_NOT = y
LOCAL_CFLAGS := $(CFG_HI_CFLAGS)
LOCAL_CFLAGS += -DLOG_TAG=\"$(LOCAL_MODULE)\"

ifeq ($(CFG_HI_CHIP_TYPE),hi3712)
    ifeq ($(CFG_CIPHER_MINI_OR_NOT),y)
        LOCAL_CFLAGS += -DCFG_CIPHER_MINI
    endif
endif
ifeq ($(CFG_HI_CIPHER_MULTICIPHER_SUPPORT),y)
    LOCAL_CFLAGS += -DCFG_HI_CIPHER_MULTICIPHER_SUPPORT
endif
ifeq ($(CFG_HI_CIPHER_HASH_SUPPORT),y)
    LOCAL_CFLAGS += -DCFG_HI_CIPHER_HASH_SUPPORT
endif

#LOCAL_SRC_FILES := $(sort $(call all-c-files-under, ./))
LOCAL_SRC_FILES := unf_cipher.c

LOCAL_C_INCLUDES := $(COMMON_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_API_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_API_INCLUDE)

LOCAL_SHARED_LIBRARIES := libcutils libutils libhi_common

include $(BUILD_STATIC_LIBRARY)
